"""Central runtime configuration and shared infrastructure for IRPS."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from logging.handlers import RotatingFileHandler
from pathlib import Path
from typing import Final


class IRPSError(Exception):
    """Base exception for expected IRPS pipeline failures."""


class ConfigurationError(IRPSError):
    """Raised when a runtime configuration is invalid."""


class ModelLoadError(IRPSError):
    """Raised when the trained detection model cannot be loaded."""


class ImageValidationError(IRPSError):
    """Raised when an input image is missing or unreadable."""


ROOT_DIR: Final[Path] = Path(__file__).resolve().parents[1]
DATA_DIR: Final[Path] = ROOT_DIR / "data"
MODEL_DIR: Final[Path] = ROOT_DIR / "models"
OUTPUT_DIR: Final[Path] = ROOT_DIR / "outputs"
LOG_DIR: Final[Path] = ROOT_DIR / "logs"
CROPS_DIR: Final[Path] = OUTPUT_DIR / "yolo_crops"
VISUALIZATION_DIR: Final[Path] = OUTPUT_DIR / "yolo_visualization"
JSON_DIR: Final[Path] = OUTPUT_DIR / "ocr_final_json"
OCR_DIR: Final[Path] = OUTPUT_DIR / "ocr_prediction"
YOLO_MODEL_PATH: Final[Path] = MODEL_DIR / "best.pt"

CLASS_MAPPING: Final[dict[str, int]] = {
    "company": 0,
    "date": 1,
    "address": 2,
    "total": 3,
}
REV_CLASS_MAPPING: Final[dict[int, str]] = {
    class_id: name for name, class_id in CLASS_MAPPING.items()
}
VALID_CLASSES: Final[tuple[str, ...]] = tuple(CLASS_MAPPING)
CLASS_COLORS: Final[dict[str, tuple[int, int, int]]] = {
    "company": (0, 0, 255),
    "date": (0, 255, 0),
    "address": (255, 0, 0),
    "total": (0, 255, 255),
}
VALID_IMAGE_SUFFIXES: Final[frozenset[str]] = frozenset(
    {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp"}
)


@dataclass(frozen=True, slots=True)
class InferenceConfig:
    """Validated parameters for a single YOLO receipt-detection request."""

    model_path: Path = YOLO_MODEL_PATH
    confidence_threshold: float = 0.25
    iou_threshold: float = 0.45
    image_size: int = 640
    device: str = "cpu"
    verbose: bool = False

    def __post_init__(self) -> None:
        object.__setattr__(self, "model_path", Path(self.model_path))
        if not 0.0 <= self.confidence_threshold <= 1.0:
            raise ConfigurationError("confidence_threshold must be between 0 and 1.")
        if not 0.0 <= self.iou_threshold <= 1.0:
            raise ConfigurationError("iou_threshold must be between 0 and 1.")
        if self.image_size <= 0:
            raise ConfigurationError("image_size must be greater than zero.")
        if not self.device.strip():
            raise ConfigurationError("device must not be empty.")


DEFAULT_INFERENCE_CONFIG: Final[InferenceConfig] = InferenceConfig()


@dataclass(frozen=True, slots=True)
class OcrConfig:
    """Quality gates used before OCR output enters the business workflow."""

    minimum_confidence: float = 0.75
    minimum_sharpness: float = 35.0
    language: str = "en"

    def __post_init__(self) -> None:
        if not 0.0 <= self.minimum_confidence <= 1.0:
            raise ConfigurationError("minimum_confidence must be between 0 and 1.")
        if self.minimum_sharpness < 0.0:
            raise ConfigurationError("minimum_sharpness must not be negative.")
        if not self.language.strip():
            raise ConfigurationError("language must not be empty.")


DEFAULT_OCR_CONFIG: Final[OcrConfig] = OcrConfig()


def ensure_runtime_directories() -> None:
    """Create only directories generated by the runtime pipeline."""
    for directory in (
        MODEL_DIR,
        LOG_DIR,
        CROPS_DIR,
        VISUALIZATION_DIR,
        JSON_DIR,
        OCR_DIR,
    ):
        directory.mkdir(parents=True, exist_ok=True)


def get_class_index(class_name: str) -> int:
    """Return a validated class ID for a receipt-field name."""
    normalized_name = class_name.strip().lower()
    try:
        return CLASS_MAPPING[normalized_name]
    except KeyError as error:
        raise ConfigurationError(
            f"Invalid receipt field '{class_name}'. Expected one of: {VALID_CLASSES}."
        ) from error


def get_logger(name: str) -> logging.Logger:
    """Return an idempotently configured, rotating IRPS logger."""
    ensure_runtime_directories()
    logger = logging.getLogger(name)
    if getattr(logger, "_irps_configured", False):
        return logger

    logger.setLevel(logging.INFO)
    logger.propagate = False
    formatter = logging.Formatter(
        "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        "%Y-%m-%d %H:%M:%S",
    )
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter)
    file_handler = RotatingFileHandler(
        LOG_DIR / "irps.log",
        maxBytes=5 * 1024 * 1024,
        backupCount=3,
        encoding="utf-8",
    )
    file_handler.setFormatter(formatter)
    logger.addHandler(console_handler)
    logger.addHandler(file_handler)
    logger._irps_configured = True  # type: ignore[attr-defined]
    return logger


__all__ = [
    "CLASS_COLORS",
    "CLASS_MAPPING",
    "CROPS_DIR",
    "ConfigurationError",
    "DATA_DIR",
    "DEFAULT_INFERENCE_CONFIG",
    "DEFAULT_OCR_CONFIG",
    "ImageValidationError",
    "InferenceConfig",
    "IRPSError",
    "JSON_DIR",
    "LOG_DIR",
    "MODEL_DIR",
    "ModelLoadError",
    "OUTPUT_DIR",
    "OCR_DIR",
    "OcrConfig",
    "REV_CLASS_MAPPING",
    "ROOT_DIR",
    "VALID_IMAGE_SUFFIXES",
    "VISUALIZATION_DIR",
    "VALID_CLASSES",
    "YOLO_MODEL_PATH",
    "ensure_runtime_directories",
    "get_class_index",
    "get_logger",
]
